### PR TITLE
add aws cloudwatch backend for json data

### PR DESCRIPTION
**Pull request by jeff-knurek**
to avoid having one extra data layer, this would be nice to have for building alerts on the log output

----
for authentication, tested by using `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` env variables in the container. also possible to run with a `~/.aws/credentials` file

### CODE REVIEW

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Thanks for your contribution @jeff-knurek SO very much appreciated!

**Comment by jeff-knurek** [comment]
uh oh
Screenshot from 2020-09-09 16-53-17

----
I don't have access to see what happened.
Related, is there an automatic docker image build/push?

**Comment by lmangani** [comment]
@jeff-knurek i don't see that error here, will check. should not be PR's fault I'm quite sure its just an outdated builder.

**Comment by jeff-knurek** [comment]
the error is on the master branch - i've got my fingers crossed its just some outdated config :wink:

**Comment by lmangani** [comment]
If it builds fine locally, it's fine. I'll rebuild the CI from scratch and see what happens later on today. Thanks again for the PR and you're welcome to the project anytime!

**Comment by adubovikov** [comment]
@jeff-knurek thank you. If you can also star our project, it will be great:  https://github.com/sipcapture/homer/stargazers

**Comment by jeff-knurek** [comment]
@lmangani what's the process for getting the image in docker hub to be updated with this change? https://hub.docker.com/r/sipcapture/hepop

**Comment by lmangani** [comment]
My bad! `+ hepop@1.0.36` pushed to npm. The current CI pipeline should do it but its borked. Will find time for an alternative or to fix it at some point hopefully.

**Comment by lmangani** [comment]
docker build in progress...

**Comment by lmangani** [comment]
@jeff-knurek the new container images should be published. Let us know if they need any work - thanks for your contribution!
Note aside, we should implement an `hepsub` agent to fetch cloudwatch data to the UI as well to make a circular connection.

**Comment by jeff-knurek** [comment]
thanks for updating the image :+1: 

another note: I only implemented to log output direct to cloudwatch, but the metrics could/should also be exported there. it's not a big priority at the moment, because we're using the influx output getting sent to `telegraf` and then having telegraf send it to cloudwatch: https://github.com/influxdata/telegraf/tree/release-1.15/plugins/outputs/cloudwatch but it would be nice to remove that complexity going forward

**Comment by lmangani** [comment]
Could you perhaps share a telegraf config relevant to HOMER users and metrics so we can add it to the wiki?

**Comment by jeff-knurek** [comment]
there's really not much needed. there's an input option to consume timeseries metric data from HEPop, and an output setting for aws/cloudwatch:
```
[[outputs.cloudwatch]]
  region = "us-east-1"
  namespace = "webrtc"
  shared_credential_file = "~/.aws/credentials"
[[inputs.http_listener]]
  service_address = ":8094"
```

**Pull request merged**
